config/routes.rb
Rails.application.routes.draw do

  root to: "atividades#index"

  get   "/login", to: "login#new"
  post  "/login", to: "login#create"
  get "/logout", to: "login#destroy"
  get "/usuarios/edit", to:"usuarios#edit"

  resources :rejeicao, as: "rejeitar"
  resources :usuarios, only: [:new, :create, :edit, :update]
  resources :comprovantes, only: [:new, :create]
  resources :declaracoes

  resources :atividades do
    member do
      get :avalia
      get :valida
      get :confirma
      get :cancela
      put :remove_arquivo
    end
  end

  get 'declaracoes', to: 'declaracoes#validar_declaracao'
  get 'validar_declaracao_index', to: 'declaracoes#validar_declaracao_index'
  post 'validar_declaracao', to: 'declaracoes#validar_declaracao'
  get "declaracao_atividades_:hora.pdf", to: 'declaracoes#declaracao_atividades', format: 'pdf', as: "declaracao_atividades"
  get "relatorio_atividades_:hora.pdf", to: 'declaracoes#relatorio_atividades', format: 'pdf', as: "relatorio_atividades"

end

app/controllers/declaracoes_controller.rb
class DeclaracoesController < ApplicationController

	def show
		redirect_to 'declaracoes/validar_declaracao'
	end

	def validar_declaracao_index
	end

  	def validar_declaracao
  		chave = []
  		(1..4).each do |i|
  			chave << params[:chave]["#{i}"].upcase
  		end
  		@declaracao = Declaracao.where(chave: chave.join(".")).first
  		if @declaracao
			render '/declaracoes/validar_declaracao'
  		else
  			redirect_to validar_declaracao_index_path, alert: 'Declaração não encontrada. Por favor, confira o CPF e a chave.'
  		end
  	end

	def declaracao_atividades
		@declaracao = Declaracao.nova_declaracao(usuario_atual)
		@declaracao.save
		@hora = Time.now.localtime
		respond_to do |format|
			format.pdf do
				pdf = DeclaracaoPdf.new(@declaracao, view_context, @hora)
				send_data pdf.render, type: "application/pdf",
				disposition: "inline"
			end
		end
	end

	def relatorio_atividades
		@declaracao = Declaracao.novo_relatorio(usuario_atual)
		@declaracao.save
		@hora = Time.now.localtime
		respond_to do |format|
			format.pdf do
	          pdf = RelatorioPdf.new(@declaracao, view_context, @hora)
	          send_data pdf.render, type: "application/pdf",
                              disposition: "inline"
            end
		end
	end

end

app/helpers/declaracoes_helper.rb
module DeclaracoesHelper
end

app/views/declaracoes/validar_declaracao.html.erb
<div class="page-header">
  <h1> Validar Declarações </h1>
</div>

<fieldset id="dados_do_aluno">
  <legend>Dados do aluno</legend>
  <div>
    <p><b>Nome:</b>
      <%= @declaracao.usuario.nome %></p>
  </div>
  <div>
    <p><b>CPF:</b> <%= @declaracao.usuario.iduff %></p>
  </div>
</fieldset>

<fieldset id="dados_da_declaracao">
  <legend>Dados da declaracao</legend>
  <div>
    <p><b>Data de emissão:</b></p>
    <p> <%= @declaracao.created_at.strftime("%d/%m/%Y %H:%M:%S") %></p>
  </div>
    <div>
    <p><b>Chave:</b></p>
    <p> <%= @declaracao.chave %></p>
  </div>
  <hr>
  <%@declaracao.tabela.each_with_index do |atividade, index| next if index == 0%>

      <p><b>Atividade <%=index%>:</b></p>
      <p>Nome: <%=atividade[0]%></p>
      <p>Descricao: <%=atividade[1]%></p>
      <p>Avaliador: <%=atividade[1]%>
      <p>Criação: <%=atividade[2]%></p>
      <p>Ultima Atualizaçao: <%=atividade[3]%></p>
      <p>Status: <%=atividade[4]%></p>
    <%end%>
  <div>
  </div>

</fieldset>

<%= link_to "Voltar", root_path, :class => 'btn btn-default' %>

app/views/declaracoes/validar_declaracao_index.html.erb
<div class="page-header">
<h1> Validar Autenticidade de Declaração </h1>
</div>

<div>
  <p>Nesta página é possível validar as declarações geradas pelo sistema de Pós-Graduação da UFF para verificar sua
    autenticidade. Toda declaração possui uma chave de validação no rodapé do documento que serve para este fim.</p>
</div>

<br>
<div>
  <p>Digite a chave e o CPF da pessoa referida na declaração nos campos abaixo para validá-la:</p>
  
  <%= form_tag(validar_declaracao_path) do %>
    <div id="validar_declaracao">
        <p>
          <%= label_tag :iduff, "CPF: " %>
          <%= text_field_tag(:iduff, nil, class: "campo_iduff") %>
        </p>
        <p>
          <%= label_tag :chave, "Chave:"%>
          <%= text_field_tag(:chave_1, nil, class: "campo_chave", name: "chave[1]", style: "width: 50px !important;") %>
          .<%= text_field_tag(:chave_2, nil, class: "campo_chave", name: "chave[2]", style: "width: 50px !important;") %>
          .<%= text_field_tag(:chave_3, nil, class: "campo_chave", name: "chave[3]", style: "width: 50px !important;") %>
          .<%= text_field_tag(:chave_4, nil, class: "campo_chave", name: "chave[4]", style: "width: 50px !important;") %>
        </p>
          <%= submit_tag "Validar", :id => "submit" , class: 'btn btn-primary'%>

    </div>
<% end %>
</div>

<script type="text/javascript">

    // $(document).ready(function ($) {
    //     $(".campo_chave").inputmask("****");
    // });

    $(document).ready(function () {
        function muda_foco_ao_atingir_tamanho(el1, el2, tam) {
            el1.keyup(function () {
                str = $(this).val()
                str = str.replace(/_/g, "")
                if (str.length == tam) {
                    el2.focus();
                }
            });
        }

        muda_foco_ao_atingir_tamanho($("#chave_1"), $("#chave_2"), 4)
        muda_foco_ao_atingir_tamanho($("#chave_2"), $("#chave_3"), 4)
        muda_foco_ao_atingir_tamanho($("#chave_3"), $("#chave_4"), 4)
        muda_foco_ao_atingir_tamanho($("#chave_4"), $("#submit"), 4)

    });
</script>