config/routes.rb
Rails.application.routes.draw do

  root to: "atividades#index"

  get   "/login", to: "login#new"
  post  "/login", to: "login#create"
  get "/logout", to: "login#destroy"
  get "/usuarios/edit", to:"usuarios#edit"

  resources :rejeicao, as: "rejeitar"
  resources :usuarios, only: [:new, :create, :edit, :update]
  resources :comprovantes, only: [:new, :create]
  resources :declaracoes

  resources :atividades do
    member do
      get :avalia
      get :valida
      get :confirma
      get :cancela
      put :remove_arquivo
    end
  end

  get 'declaracoes', to: 'declaracoes#validar_declaracao'
  get 'validar_declaracao_index', to: 'declaracoes#validar_declaracao_index'
  post 'validar_declaracao', to: 'declaracoes#validar_declaracao'
  get "declaracao_atividades_:hora.pdf", to: 'declaracoes#declaracao_atividades', format: 'pdf', as: "declaracao_atividades"
  get "relatorio_atividades_:hora.pdf", to: 'declaracoes#relatorio_atividades', format: 'pdf', as: "relatorio_atividades"

end

app/models/atividade.rb
class Atividade < ActiveRecord::Base
	
	belongs_to :aluno
	belongs_to :professor
	validates_presence_of :nome, :aluno_id
	has_many :comprovantes, :dependent => :destroy
	has_many :declaracoes

	# validates_attachment_size :arquivos[], :less_than => 2.megabyte, :if => :arquivo, :message => "deve ser menor que 2 MB", :on => :create
 #   	validates_attachment_content_type :arquivo, :content_type => 'application/pdf', :message => :invalid, :if => :arquivo


	STATUS = ["TODOS", "REGISTRADA", "PROCESSANDO", "VALIDADA", "REJEITADA", "CONFIRMADA", "CANCELADA"]
	
	REGISTRADA = 1
	VALIDADA = 2
	REJEITADA = 3
	CONFIRMADA = 4
	CANCELADA = 5
	
end

app/controllers/atividades_controller.rb
class AtividadesController < ApplicationController
  before_filter :authorize_usuario
  before_action :set_atividade, only: [:show, :edit, :update, :destroy, :avalia, :valida, :confirma, :cancela, :remove_arquivo]

  # GET /atividades
  # GET /atividades.json
  def index
    case usuario_atual.categoria
      when "Aluno"
        @atividades = Atividade.where({usuario_id: usuario_atual.id}).group("status", "id")
      when "Professor"
         @atividades = Atividade.where({professor: [usuario_atual.nome , nil]})
      when "Administrador" || "Coordenacao" || "Secretaria"
        @atividades = Atividade.all.group("status", "id")
      else
         @atividades = Atividade.all.group("status", "id")
    end
    respond_to do |format|
      format.html
    end
  end

  # GET /atividades/1
  # GET /atividades/1.json
  def show
  end

  # GET /atividades/new
  def new
    @atividade = usuario_atual.atividades.build
  end

  # GET /atividades/1/edit
  def edit
  end

  # POST /atividades
  # POST /atividades.json
  def create

    @atividade = usuario_atual.atividades.build(atividade_params)
    @atividade.aluno = usuario_atual.nome
    @atividade.status = "Registrada" #TODO check set default options

    respond_to do |format|
      if @atividade.save
        # UsuarioMailer.novo_pedido_email(usuario_atual, "registrada").deliver_now
        format.html { redirect_to @atividade, notice: 'Atividade foi criada com sucesso.' }
        format.json { render :show, status: :created, location: @atividade }
      else
        format.html { render :new, alert: 'Atividade nao pode ser criada' }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atividades/1
  # PATCH/PUT /atividades/1.json
  def update
    respond_to do |format|

      if @atividade.update(atividade_params)

        if params[:arquivos]

          params[:arquivos].each_with_index { |arquivo, index|

            @comprovante = Comprovante.novo_comprovante(arquivo, index, usuario_atual.nome)
            @comprovante.atividade = @atividade
            if !@comprovante.save
              flash[:alert] = "Nao foi possivel salvar o comprovante"
            end
          }
        end

        format.html { redirect_to @atividade, notice: 'Atividade foi atualizada.' }
        format.json { render :show, status: :ok, location: @atividade }
      else
        format.html { render :edit }
        format.json { render json: @atividade.errors, status: :unprocessable_entity }
      end
    end
  end

  def avalia
    ac_status = "Processando"
    if @atividade.update_attributes(status: ac_status, professor: usuario_atual.id.to_s)
        UsuarioMailer.novo_pedido_email(usuario_atual, ac_status ).deliver_now
        redirect_to @atividade, notice: 'Atividade foi atualizada.'
      else
        render json: @atividade.errors, status: :unprocessable_entity
      end
  end

  def valida
   ac_status = "Validada"
    if @atividade.update_attributes(status: ac_status)
      UsuarioMailer.novo_pedido_email(usuario_atual, ac_status).deliver_now
      redirect_to @atividade, notice: 'Atividade foi atualizada.'
    else
      render json: @atividade.errors, status: :unprocessable_entity
    end
  end

  def confirma
    ac_status = "Confirmada"
      if @atividade.update_attributes(status: ac_status)
        UsuarioMailer.novo_pedido_email(usuario_atual, ac_status).deliver_now
        redirect_to @atividade, notice: 'Atividade foi atualizada.'
      else
        render json: @atividade.errors, status: :unprocessable_entity
      end
  end

  def cancela
    ac_status = "Cancelada"
    if @atividade.update_attributes(status: ac_status)
      UsuarioMailer.novo_pedido_email(usuario_atual, ac_status).deliver_now
      redirect_to @atividade, notice: 'Atividade foi atualizada.'
      else
        render json: @atividade.errors, status: :unprocessable_entity
      end
  end

  # DELETE /atividades/1
  # DELETE /atividades/1.json
  def destroy
    @atividade.destroy
    respond_to do |format|
      format.html { redirect_to atividades_url, notice: 'Atividade foi deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  def remove_arquivo

     c = @atividade.comprovantes[params[:comp_index].to_i]
     c.destroy
     @atividade.save
     respond_to do |format|
       format.html { redirect_to @atividade, notice: 'Arquivo removido.' }
       format.json { render :show, status: :ok, location: @atividade }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atividade
      @atividade = Atividade.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atividade_params
      params.require(:atividade).permit(:nome, :status, :professor, :motivo)
    end
end

app/views/atividades/_atividade.html.erb
<% @atividades.each do |atividade| %>
<tr class='<%= atividade.status %> clickable-row' data-href='/atividades/<%=atividade.id%>'>
	<td><%= atividade.nome %></td>
	<td><%= tem_comprovante(atividade.comprovante_ids) %></td>
	<td><%= atividade.aluno.usuario.nome %></td>
	<td><%= atividade.professor.usuario.nome %></td>
	<td><%= atividade.created_at.localtime.strftime("%d-%m-%y") %></td>
	<td><%= atividade.updated_at.localtime.strftime("%d-%m-%y") %></td>
	<td class="status"><%= atividade.status %></td>
	<td>
	<% if usuario_atual == atividade.aluno.usuario && atividade.status == "Registrada"%>
  	<%= link_to 'Excluir',  atividade_path(atividade.id), method: :delete, data: {confirm: 'Deseja confirmar?'}, class:'btn btn-danger' %></td>
  <%end%>
</tr>
<% end %>

app/views/atividades/_form.html.erb
<%= form_for (@atividade) , :html => { :multipart => true } do |f| %>
  
  <% if @atividade.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <p><%= pluralize(@atividade.errors.count, "erro") %> ao salvar esta Atividade</p>

      <ul>
      <% @atividade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div>

    <div class="dropdown">
      <%= f.label "Tipo de Atividade Complementar: ", :class => 'control-label' %><br>
      <%= f.collection_select(:nome, TipoAtividade.all, :nome, :nome, { :prompt => 'Tipo de Atividade Complementar', :selected => @atividade.nome }, { class: 'dropdown' }) %>
    </div>
<br>

    <div>
    <%= f.label "Descrição: "%><br>
    <%= f.text_area :descricao%>
    </div>

  <div class="control-group">
    <%= f.label :comprovantes, class: 'control-label' %>
    <div class="controls">
    <p><% @atividade.comprovantes.each do |comprovante|%>
    <a href="<%= comprovante.arquivo.url %>"><%= comprovante.arquivo_file_name %></a> | 
    <% end %></p>
      <%= hidden_field_tag "comprovante_ids[]", @atividade.comprovante_ids %>
      <%= file_field_tag "arquivos[]", type: :file, multiple: false, accept: 'application/pdf' %>
      <%= file_field_tag "arquivos[]", type: :file, multiple: false, accept: 'application/pdf' %>

    </div>
  </div>



  </div>

  </br>  <%= f.submit "Salvar", class: 'btn btn-primary' %>
  <%= link_to 'Voltar', atividades_path, class:"btn btn-default" %>
<% end %>

app/views/atividades/edit.html.erb
<div class="page-header">
<h1>Editar Atividade Complementar</h1>
</div>

<%= render 'form' %>

app/views/atividades/index.html.erb
<div class="page-header">
  <h1>Lista de Atividades</h1>
</div>

<div class="panel panel-default table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Documento</th>
      <th>Aluno</th>
      <th>Professor</th>
      <th>Data de<br>Registro</th>
      <th>Última<br>Atualização</th>
      <th>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Status
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
          <% Atividade::STATUS.each do |status| %>
            <li><a class="filtro"><%= status.capitalize %></a></li>
            <%end%>
          </ul>
        </div>
      </th>
    </tr>
  </thead>
  <tbody>
    <%= render 'atividade',  collection: @atividades %>
  </tbody>

</table>
</div>

<div class="btn-group" role="group">
<% if usuario_atual.categoria == "Aluno" || usuario_atual.categoria == "Administrador" %>
  <%= link_to 'Nova Atividade', new_atividade_path, class:"btn btn-primary" %>
<%end%>
<%= link_to 'Gerar Declaração', declaracao_atividades_path(format: "pdf", hora: Time.now.to_i), method: :get, class:"btn btn-default", target: "_tab"%>
<%= link_to 'Gerar Relatório', relatorio_atividades_path(format: "pdf", hora: Time.now.to_i), method: :get, class:"btn btn-default", target: "_tab"%>

</div>

<script type="text/javascript">
  $(".filtro").click(function(){
      status = $(this).text();
      if(status == "Todos"){
        $('tbody tr').show()
      }
      else{
       $('tbody tr').show().not('.' +  status).hide();
     }
  });

  $(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.document.location = $(this).data("href");
    });
  });
</script>

app/views/atividades/new.html.erb
<div class="page-header">
	<h1>Cadastrar Atividade Complementar</h1>
</div>

<%= render 'form' %>

app/views/atividades/show.html.erb
  <div class="page-header">
  <h1>Atividade Complementar - <%= @atividade.nome %></h1>
  </div>

  <p>
    <strong>Nome:</strong>
    <%= @atividade.nome %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @atividade.status %>
  </p>

  <p>
    <strong>Professor:</strong>
    <%= @atividade.professor.usuario.nome %>
  </p>

  <p>
    <strong>Documento:</strong>
    <br><% @atividade.comprovantes.each_with_index do |comprovante, index|%>
      Arquivo <%= index+1 %>:
      <a href="<%= comprovante.arquivo.url %>" target="_tab"><%= comprovante.arquivo_file_name %></a> 
      <% if @atividade.status == "Registrada" %>
      <%= link_to("<span class=\"glyphicon glyphicon\-remove\" aria-hidden=\"true\"></span>".html_safe, {action: :remove_arquivo, id: @atividade.id}, method: :put, data: { confirm: 'Deseja remover este arquivo?' })%> 
      <%end%>
    <br>
    <% end %>
  </p>

  <p>
    <strong>Aluno:</strong>
    <%= @atividade.aluno.usuario.nome %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= @atividade.descricao %>
  </p>

  <%if @atividade.status == "Rejeitada"%>
    <p>
      <strong>Motivo de Rejeicao:</strong>
      <%= @atividade.motivo %>
    </p>
  <%end%>

<!-- Açoes do usuario -->

<div class="btn-group" role="group">

  <%if usuario_atual.categoria == "Professor" || usuario_atual.categoria == "Administrador"%>

    <% if @atividade.professor.nil?%>
      <%= link_to 'Avaliar', avalia_atividade_path(@atividade.id), class:'btn btn-warning' %>
    <%elsif @atividade.status == "Processando"%>
      <%= link_to 'Validar', valida_atividade_path(@atividade.id), class:'btn btn-success' %>
      <%= link_to 'Rejeitar', edit_rejeitar_path(@atividade.id), class:'rejeita_ac btn btn-danger' %>
    <%end%>

  <%end%>

  <%if @atividade.status == 'Validada' && (usuario_atual.categoria == "Coordenacao" || usuario_atual.categoria == "Administrador" )%>
    <%= link_to 'Confirmar', confirma_atividade_path(@atividade.id), class:'btn btn-success' %>
    <%= link_to 'Cancelar', cancela_atividade_path(@atividade.id), class:'btn btn-danger' %>
  <%end%>
  <% if usuario_atual == @atividade.aluno.usuario && @atividade.status == "Registrada"%>
  <%= link_to 'Excluir',  atividade_path(@atividade.id), method: :delete, data: {confirm: 'Deseja confirmar?'}, class:'btn btn-danger' %>
  <%end%>

  <%= link_to 'Voltar', atividades_path, class:'btn btn-default' %>

</div>