config/routes.rb
Rails.application.routes.draw do

  root to: "atividades#index"

  get   "/login", to: "login#new"
  post  "/login", to: "login#create"
  get "/logout", to: "login#destroy"
  get "/usuarios/edit", to:"usuarios#edit"

  resources :rejeicao, as: "rejeitar"
  resources :usuarios, only: [:new, :create, :edit, :update]
  resources :comprovantes, only: [:new, :create]
  resources :declaracoes

  resources :atividades do
    member do
      get :avalia
      get :valida
      get :confirma
      get :cancela
      put :remove_arquivo
    end
  end

  get 'declaracoes', to: 'declaracoes#validar_declaracao'
  get 'validar_declaracao_index', to: 'declaracoes#validar_declaracao_index'
  post 'validar_declaracao', to: 'declaracoes#validar_declaracao'
  get "declaracao_atividades_:hora.pdf", to: 'declaracoes#declaracao_atividades', format: 'pdf', as: "declaracao_atividades"
  get "relatorio_atividades_:hora.pdf", to: 'declaracoes#relatorio_atividades', format: 'pdf', as: "relatorio_atividades"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sisac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/" title="SisAC">SISAC</a>
    </div>
    <div class="navbar-collapse collapse">
        <ul id="app-menu" class="nav navbar-nav navbar-right">
          <li><a href="/validar_declaracao_index">Validar Declaração</a></li>
          <% if usuario_atual %>
            <% if usuario_atual.categoria == "Aluno" %>
          
              <li><%= link_to "Nova Atividade", new_atividade_path %></li>
              <li><%= link_to "Atividades", atividades_path %></li>
            <%end%>
            <li><a><%= usuario_atual.categoria.capitalize %>: <%= usuario_atual.nome.capitalize %></a></li>
            <li><%= link_to "Logout", logout_path %></li>
          <% else %>

            
            <li><%= link_to "Login", login_path %></li> 
          <% end %>


        </ul>
      </div>
    </div>
</div>
 
<div id="main-container" class="container">
	<div class="row">	

    <div class="container">

      <% if notice %><p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %><p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
	</div>
</div>

<nav class="navbar navbar-fixed-bottom">
  <footer class="footer">
  	<div class="container">
  		<p style="color:#DFDFDF">&copy; Universidade Federal Fluminense 2014</p>
  	</div>
  </footer>
</nav>

</body>
 <script>
//   $(".rejeita_ac").click(function(){
        
//   $( "<strong>Motivo da rejeicão:</strong><p><textarea cols=\"50\" rows=\"10\"></textarea></p>" ).appendTo( ".motivo_rejeicao" );
//   })
// </script>
</html>